# Generated by Django 4.1.5 on 2023-11-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='nascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
    ]
