# Generated by Django 4.1.5 on 2024-01-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano', '0008_remove_paciente_sexo_paciente_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuferencias',
            name='rcq',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15, verbose_name='Rcq'),
            preserve_default=False,
        ),
    ]
