# Generated by Django 4.2.3 on 2024-02-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano', '0010_alimentos_categorias_nutrientes_valorenegeticos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valorenegeticos',
            name='alimento',
        ),
        migrations.RemoveField(
            model_name='valorenegeticos',
            name='nutriente',
        ),
        migrations.AddField(
            model_name='alimentos',
            name='calcio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Cálcio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alimentos',
            name='carboidrato',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Carboidrato'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alimentos',
            name='cinzas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Cinzas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alimentos',
            name='cobre',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Cobre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alimentos',
            name='colesterol',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Colesterol'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alimentos',
            name='energiakcal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Energia kcal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alimentos',
            name='energiakj',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Energia kj'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alimentos',
            name='ferro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Ferro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alimentos',
            name='fibraalimentar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Fibra Alimentar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alimentos',
            name='fosforo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Fósforo '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alimentos',
            name='lipideos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Lipídeos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alimentos',
            name='magnesio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Magnésio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alimentos',
            name='manganes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Manganês'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alimentos',
            name='monoinsaturados',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Monoinsaturados'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alimentos',
            name='niacina',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Niacina'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alimentos',
            name='piridoxina',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Piridoxina'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alimentos',
            name='poliinsaturados',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Poliinsaturados'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alimentos',
            name='potassio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Potássio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alimentos',
            name='proteina',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Proteína'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alimentos',
            name='retinol',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Retinol'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alimentos',
            name='riboflavina',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Riboflavina'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alimentos',
            name='saturados',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saturados'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alimentos',
            name='sodio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Sódio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alimentos',
            name='tiamina',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tiamina'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alimentos',
            name='umidade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Umidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alimentos',
            name='vitaminac',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Vitamina C'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alimentos',
            name='zinco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Zinco'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Nutrientes',
        ),
        migrations.DeleteModel(
            name='Valorenegeticos',
        ),
    ]
