# Generated by Django 4.2.3 on 2024-02-07 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plano', '0011_remove_valorenegeticos_alimento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alimentos',
            name='monoinsaturados',
        ),
        migrations.RemoveField(
            model_name='alimentos',
            name='poliinsaturados',
        ),
        migrations.RemoveField(
            model_name='alimentos',
            name='saturados',
        ),
    ]
