# Generated by Django 4.2.3 on 2024-02-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano', '0013_remove_categorias_ativo_remove_categorias_criado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentos',
            name='umidade',
            field=models.FloatField(verbose_name='Umidade'),
        ),
    ]
