# Generated by Django 4.2.3 on 2024-02-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano', '0014_alter_alimentos_umidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentos',
            name='energiakcal',
            field=models.FloatField(verbose_name='Energia kcal'),
        ),
    ]
