# Generated by Django 4.2.3 on 2024-02-08 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plano', '0016_alter_alimentos_calcio_alter_alimentos_carboidrato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gorduras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saturados', models.FloatField(verbose_name='Saturados')),
                ('monoinsaturados', models.FloatField(verbose_name='Monoinsaturados')),
                ('poliinsaturados', models.FloatField(verbose_name='Poliinsaturados')),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plano.alimentos')),
            ],
        ),
    ]
