# Generated by Django 4.2.3 on 2024-02-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano', '0017_gorduras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietas',
            name='quantidade',
            field=models.FloatField(verbose_name='Quantidade'),
        ),
    ]
